name: test
on:
  push:
  workflow_dispatch:
jobs:
  mac-test:
    name: test
    runs-on: macos-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3

      - name: Test Tools install.
        run: ./mac-install.sh

      # # 上記までの処理が成功した場合、以下のSlack通知処理が実行される
      # - name: Slack Notification Success
      #   uses: rtCamp/action-slack-notify@v2
      #   env:
      #     SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      #     SLACK_COLOR: '#5cb85c'
      #     SLACK_TITLE: 'Success to Installed :rocket:'
      #     SLACK_MESSAGE: ':closed_book: ${{ github.repository }}'

      # # 上記までの処理のいずれかが失敗した場合、以下のSlack通知処理が実行される
      # - name: Slack Notification Failure
      #   if: failure()
      #   uses: rtCamp/action-slack-notify@v2
      #   env:
      #     SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      #     SLACK_COLOR: '#dc143c'
      #     SLACK_TITLE: 'Failure to Installed :boom:'
      #     SLACK_MESSAGE: ':closed_book: ${{ github.repository }}'
